### ISSUE TITLE
Можливість деактивації анкети.

### ISSUE THREAD

**Issue by Iryna-Ivasko** [msp4/manager#5]
Треба зробити можливість деактивувати та активувати анкети, щоб ми могли "фільтрувати" анкети, що будуть відображатися клієнтам. І показувати їм тільки готові, завершені анкети, і при цьому в нас залишались копії "старих" ще не перероблених анкет.

**Comment by vladmokryi** [comment]
![image](https://cloud.githubusercontent.com/assets/13148141/9643738/73986b06-51cc-11e5-92ef-168d778f89eb.png)
перевіряй

**Comment by Iryna-Ivasko** [comment]
Коли на менеджері зробила анкету неактивною
![image](https://cloud.githubusercontent.com/assets/12249275/9732756/f578f42c-562e-11e5-8bc9-e063efd57404.png)
а після цього створила нове дослідження на клієнті, то вибралась неактивна (заблокована анкета) анкета 
![image](https://cloud.githubusercontent.com/assets/12249275/9732777/2360e4e4-562f-11e5-9443-10593ed91cb9.png)

**Comment by vladmokryi** [comment]
В тому списку присутні анкети, які ти використовувала на цьому ж акаунті тільки в інших дослідженнях

**Comment by Iryna-Ivasko** [comment]
Прийнято, закриваю
